//Este archivo solo es para pruebas de la API
//Usando El httpClient en VSCode

###
POST http://localhost:9000/api/ingreso HTTP/1.1
Content-Type: application/json

{
    "typePay": "ingreso",
    "quantity": 20000,
    "category": "comida",
    "date": "22/05/2005"
}

###
GET http://localhost:9000/api/ingreso HTTP/1.1

###
GET http://localhost:9000/api/personaMasculino HTTP/1.1

###
GET http://localhost:9000/api/personaFemenino HTTP/1.1

###
GET http://localhost:9000/api/persona/6214524592953c12663f846f HTTP/1.1

###
PUT http://localhost:9000/api/ingreso/622d5d12bb39a957cb8bc550 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Julie",
    "fecha_nacimiento": "04/04/2001",
    "sexo": "femenino"
}

###
DELETE http://localhost:9000/api/ingreso/622e54d422a18e0d34b58d56 HTTP/1.1

